### ISSUE TITLE
[BUG]: differing chevron icons

### ISSUE THREAD

**Issue by PerilousBooklet** [drmargarido/TodoTreeView#20]
The chevron icons in the expanded mode differ from the ones in the not-expanded mode.
![image](https://github.com/user-attachments/assets/436c66d2-edfd-4d1e-ae96-eebdb90af44f)
![image](https://github.com/user-attachments/assets/171008ed-5af2-4d2d-85dd-47640d3f4b6d)

**Comment by PerilousBooklet** [comment]
I'm not sure if you use [Fontello](https://fontello.com/) to create the icon font, but it would be cleaner and easier to do so. You could just copy the chevron icons from the [nonicons](https://github.com/yamatsum/nonicons/) plugin for example, or add the ones you want.

**Comment by drmargarido** [comment]
I'm not loading any special font. I'm using the default style font that the editor already has.
You can see an example of it's usage here: https://github.com/drmargarido/TodoTreeView/blob/master/todotreeview-xl.lua#L474

Don't really want to hardcode a font since this way people can customize the font and it applies directly to everything.

**Comment by drmargarido** [comment]
Just did some tests and seems to be specific to LiteXL, on original Lite it doesn't differ.
![imagem](https://github.com/user-attachments/assets/822ebb1b-a782-4317-9456-1a9abf27ba9f)

**Comment by drmargarido** [comment]
![image](https://github.com/user-attachments/assets/0e3e03a2-3334-4a22-8f8a-666d425dfa79)
Issue fixed with the commit https://github.com/drmargarido/TodoTreeView/commit/218b811b9b180f78a00e9b12757f47a1d880317e
