### ISSUE TITLE
Tags not recognized if at the beginning of a line or alone

### ISSUE THREAD

**Issue by Soikk** [drmargarido/TodoTreeView#6]
The plugin only recognizes keywords if they're preceded by a character. If the keyword is at the start of a line, it won't be recognized.
I'm not sure if this is intended behavior or not.
I believe this is fixed by changing line 108 in the plugin file (todotreeview-xl.lua) from
```      local match_str = "[^a-zA-Z_\"'`]"..todo_tag.."[^\"'a-zA-Z_`]+"```
to
```      local match_str = "[^a-zA-Z_\"'`]*"..todo_tag.."[^\"'a-zA-Z_`]+"```

I should also mention that the plugin also only recognizes tags if they're succeeded by a character, which again I'm not sure is intended behavior. This fix is as simple as the previous, changing
```      local match_str = "[^a-zA-Z_\"'`]"..todo_tag.."[^\"'a-zA-Z_`]+"```
to
```      local match_str = "[^a-zA-Z_\"'`]"..todo_tag.."[^\"'a-zA-Z_`]*"```

Overall, the two changes combined would leave line 108 like this
```      local match_str = "[^a-zA-Z_\"'`]*"..todo_tag.."[^\"'a-zA-Z_`]*"```

**Comment by drmargarido** [comment]
Hello, thanks for raising the issue.

The one at the start of the line is an issue I hadn't noticed since I usually use tags in comments which are prefixed with something like `#`, `--` or `//`. I can see the use case of using them at the start of the line in a documentation file where the comments are not needed.

The one at the end of line is a different situation. Tags with the current implementation need to have a description after them. So here the question is if we want to allow tags without description or not. I could see this being useful in some situations were I use just an isolated `DEBUG` or `CLEANUP` tag. I just need to decide what to use as a default description. Maybe I just put "empty" or the line number in the description.

I will need to test other implementations, the `*` in the initial pattern will allow for 0 matches of that, which means something like `abcTODO` will be detected. Also there are other similar cases with the `*` on the last one.

**Comment by Soikk** [comment]
> The one at the start of the line is an issue I hadn't noticed since I usually use tags in comments which are prefixed with something like `#`, `--` or `//`. I can see the use case of using them at the start of the line in a documentation file where the comments are not needed.
> 
> The one at the end of line is a different situation. Tags with the current implementation need to have a description after them. So here the question is if we want to allow tags without description or not. I could see this being useful in some situations were I use just an isolated `DEBUG` or `CLEANUP` tag. I just need to decide what to use as a default description. Maybe I just put "empty" or the line number in the description.

That's exactly what I thought. I find it useful to leave 'FIX' or 'TODO' tags scattered around places to come back later to, and your plugin is a great tool for remembering these tags.

> I will need to test other implementations, the `*` in the initial pattern will allow for 0 matches of that, which means something like `abcTODO` will be detected. Also there are other similar cases with the `*` on the last one.

Hmm, that wouldn't really be ideal. Maybe these should be configurable options. Still, someone with enough regex knowledge could fine tune their own plugin for their own purposes. I'm keen to see what you choose to do with this.

**Comment by drmargarido** [comment]
Ok, problems fixed in master with commit a937104.
Now tags are detected if they are at start and at the end of lines .
If they are at the end and don't have a description a "blank" description will appear on them.
